### ISSUE TITLE
Does this plugin work? (Can't make it work)

### ISSUE THREAD

**Issue by gamer003** [Aberinkula/HitboxPlugin#1]
Followed the installation instructions in the README to install the 2 files.

Using the latest Rocket League (v1.56) and the latest Bakkesmod.

In Freeplay the hitbox does not appear. The plugin appears when I press F2 and go to the `Plugins` tab, but it doesn't have any effect in the game (in free play).

None of the commands like `cl_soccar_showhitbox` show in the console as available.

**Comment by Aberinkula** [comment]
@gamer003 If the commands aren't working, I'm guessing the plugin isn't loaded?  Have you tried typing 'plugin load hitboxplugin' in the console, or adding that command to the plugins.cfg file?

**Comment by gamer003** [comment]
Ah, that did it. Thanks!

I opened a PR to make the README more clear.

**Comment by sshaikh08** [comment]
which console are you referring to? Rocket League doesn't seem to have a console and I'm having trouble finding it in bakkesmod ingame menu
